# Generated by Django 3.2.16 on 2024-07-20 17:36

from django.db import migrations, models
import django.db.models.deletion
import test_shop.settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('desc', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to=test_shop.settings.set_image_name, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('desc', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to=test_shop.settings.set_image_name, verbose_name='Изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorys', to='shop.category')),
            ],
            options={
                'verbose_name': 'подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('desc', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to=test_shop.settings.set_image_name, verbose_name='Изображение')),
                ('price', models.PositiveIntegerField(verbose_name='Цена товара')),
                ('image_medium', models.ImageField(upload_to=test_shop.settings.set_image_name, verbose_name='Изображение (M)')),
                ('image_small', models.ImageField(upload_to=test_shop.settings.set_image_name, verbose_name='Изображение (S)')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='shop.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('title',),
            },
        ),
    ]
